version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    env_file: ./.env.dev
    environment:
      - MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL=true
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=ecommerce-user
      - MYSQL_PASSWORD=ecommerce-user-pwd
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - ecommerce-network
  cache:
    image: redis/redis-stack
    restart: unless-stopped
    env_file: ./.env.dev
    ports:
      - 6379:6379
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD} --loadmodule /opt/redis-stack/lib/rejson.so --loadmodule /opt/redis-stack/lib/redisearch.so
    networks:
      - ecommerce-network
  app:
    command:
      [
        './wait-for-it.sh',
        'mysqldb:3306',
        '--',
        'nodemon',
        '--watch',
        'packages/ecommerce-server',
        '--exec',
        'npm',
        'run',
        'dev',
      ]
    depends_on:
      mysqldb:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: ./.env.dev
    ports:
      - 8080:8080
    volumes:
      - ./packages/ecommerce-server:/usr/ecommerce-monorepo/packages/ecommerce-server
    stdin_open: true
    tty: true
    networks:
      - ecommerce-network

volumes:
  db:

networks:
  ecommerce-network:
    driver: bridge
