FROM node:18

WORKDIR /usr/ecommerce-monorepo
COPY package*.json ./
COPY nx.json ./
COPY packages ./packages
COPY wait-for-it.sh ./wait-for-it.sh
RUN chmod +x ./wait-for-it.sh
RUN rm ./packages/ecommerce-cache/dist -rf
RUN rm ./packages/ecommerce-config/dist -rf
RUN rm ./packages/ecommerce-customer/dist -rf
RUN rm ./packages/ecommerce-data-types/dist -rf
RUN rm ./packages/ecommerce-db/dist -rf
RUN rm ./packages/ecommerce-magento/dist -rf
RUN rm ./packages/ecommerce-server/dist -rf
RUN rm ./packages/ecommerce-web3/dist -rf
RUN rm ./packages/ecommerce-webhooks/dist -rf
RUN rm ./packages/ecommerce-websocket/dist -rf
RUN rm ./packages/ecommerce-woocommerce/dist -rf
RUN rm ./packages/ecommerce-server/public/swagger.json -f
RUN rm ./packages/ecommerce-server/src/routes/routes.ts -f
RUN apt-get update && apt-get install -y nano
 
RUN npm ci
# RUN npm i -g nodemon
# Building all the packages
RUN npm run build