version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    env_file: ./.env.prod
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL=true
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  app:
    command: ['./wait-for-it.sh', 'mysqldb:3306', '--', 'npm', 'run', 'dev']
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env.prod
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes:
  db:
