services:
  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    env_file: ./.env.prod
    environment:
      - MYSQL_DATABASE
      - MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL=true
      - MYSQL_ROOT_PASSWORD=h-fPesa_g4WXEjdt
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - ecommerce-network
  redis-debug:
    image: redis/redis-stack-server
    restart: unless-stopped
    env_file:
      - ./.env.prod
    ports:
      - target: 6379
        published: ${REDIS_PORT}
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD} --loadmodule /opt/redis-stack/lib/rejson.so --loadmodule /opt/redis-stack/lib/redisearch.so
    networks:
      - ecommerce-network
  python-service:
    build:
      context: .
      dockerfile: Dockerfile.py
    env_file:
      - .env.prod
    volumes:
      - ./process-image:/usr/src/app
    ports:
      - '${PYTHON_PORT}:${PYTHON_PORT}'
    networks:
      - ecommerce-network
  app-debug:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ['./wait-for-it.sh', 'mysqldb:3306', '--', 'npm', 'run', 'debug']
    depends_on:
      - mysqldb
    restart: unless-stopped
    env_file: ./.env.dev
    ports:
      - $PORT:$PORT
      - $WS_PORT:$WS_PORT
      - 9229:9229
    stdin_open: true
    tty: true
    volumes:
      - server_code:/usr/ecommerce-monorepo/packages/ecommerce-server
      - /usr/ecommerce-monorepo/node_modules
    networks:
      - ecommerce-network

volumes:
  db:
  server_code:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/packages/ecommerce-server
      o: bind

networks:
  ecommerce-network:
    driver: bridge
