version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    env_file: ./.env.dev
    environment:
      - MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL=true
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - ecommerce-network
  app:
    # command: ['./wait-for-it.sh', 'mysqldb:3306', '--', 'npm', 'run', 'dev']
    command:
      [
        './wait-for-it.sh',
        'mysqldb:3306',
        '--',
        'nodemon',
        '--watch',
        'packages/ecommerce-server',
        '--exec',
        'npm',
        'run',
        'dev',
      ]
    depends_on:
      mysqldb:
        condition: service_started
    build: .
    restart: unless-stopped
    env_file: ./.env.dev
    ports:
      - 8080:8080
    volumes:
      - ./packages/ecommerce-server:/usr/ecommerce-monorepo/packages/ecommerce-server
    # volumes:
    #   - .:/usr/ecommerce-monorepo # map your local code into the Docker container
    stdin_open: true
    tty: true
    networks:
      - ecommerce-network
    # command: ['npm', 'run', 'dev']

volumes:
  db:

networks:
  ecommerce-network:
    driver: bridge
