FROM node:18

WORKDIR /usr/ecommerce-monorepo

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy nx.json file
COPY nx.json ./

# Copy the packages directory
COPY packages ./packages

# Copy the wait-for-it.sh script
COPY wait-for-it.sh ./wait-for-it.sh
RUN chmod +x ./wait-for-it.sh

# Install development dependencies
RUN npm install

# Install nodemon and ts-node globally
RUN npm install -g nodemon typescript
# Building all the packages
RUN npm run build

