services:
  mysqldb-prod:
    image: mysql:8.0.33
    restart: unless-stopped
    env_file:
      - ./.env.prod
    environment:
      - MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL=true
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - db:/var/lib/mysql
  redis-prod:
    image: redis/redis-stack-server
    restart: unless-stopped
    env_file:
      - ./.env.prod
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD} --loadmodule /opt/redis-stack/lib/rejson.so --loadmodule /opt/redis-stack/lib/redisearch.so
    networks:
      - ecommerce-network
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command:
      ['./wait-for-it.sh', 'mysqldb-prod:3306', '--', 'npm', 'run', 'prod']
    depends_on:
      - mysqldb-prod
    restart: unless-stopped
    env_file:
      - ./.env.prod
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
    volumes:
      - server_code:/usr/ecommerce-monorepo/packages/ecommerce-server
      - /usr/ecommerce-monorepo/node_modules
    networks:
      - ecommerce-network

volumes:
  db:
  server_code:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/packages/ecommerce-server
      o: bind

networks:
  ecommerce-network:
    driver: bridge
